"""added on cascade to labels

Revision ID: 302065e748c0
Revises: b38a34860fc5
Create Date: 2025-11-30 14:58:34.506758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302065e748c0'
down_revision: Union[str, Sequence[str], None] = 'b38a34860fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('labels_version_id_fkey'), 'labels', type_='foreignkey')
    op.drop_constraint(op.f('labels_image_id_fkey'), 'labels', type_='foreignkey')
    op.create_foreign_key(None, 'labels', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'labels', 'versions', ['version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.create_foreign_key(op.f('labels_image_id_fkey'), 'labels', 'images', ['image_id'], ['id'])
    op.create_foreign_key(op.f('labels_version_id_fkey'), 'labels', 'versions', ['version_id'], ['id'])
    # ### end Alembic commands ###
