"""added labels and versions

Revision ID: b38a34860fc5
Revises: 9c60272a743c
Create Date: 2025-11-30 14:03:32.174457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b38a34860fc5'
down_revision: Union[str, Sequence[str], None] = '9c60272a743c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('version_id', sa.UUID(), nullable=True))
    op.alter_column('labels', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_labels_version'), table_name='labels')
    op.create_foreign_key(None, 'labels', 'versions', ['version_id'], ['id'])
    op.drop_column('labels', 'version')
    op.add_column('versions', sa.Column('name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_versions_version'), table_name='versions')
    op.create_index(op.f('ix_versions_name'), 'versions', ['name'], unique=False)
    op.drop_column('versions', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_versions_name'), table_name='versions')
    op.create_index(op.f('ix_versions_version'), 'versions', ['version'], unique=False)
    op.drop_column('versions', 'name')
    op.add_column('labels', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.create_index(op.f('ix_labels_version'), 'labels', ['version'], unique=False)
    op.alter_column('labels', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('labels', 'version_id')
    # ### end Alembic commands ###
